# Generated by Django 5.2.7 on 2025-10-27 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='course_img',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='profile_picture',
        ),
    ]
