# Generated by Django 5.2.7 on 2025-10-27 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video',
            field=models.FileField(max_length=300, upload_to='videos/'),
        ),
    ]
