# Generated by Django 5.2.7 on 2025-11-06 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='contact_email',
        ),
        migrations.AlterField(
            model_name='video',
            name='skills',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
